### ISSUE TITLE
Nogatzify the folder structure

### ISSUE THREAD

**Issue by stkdiretto** [UlmApi/uulm-map#3]
And @fnogatz spoke thusly: „Die Ordnerstruktur ist mal voll kacke!“

Therefore, adhere to the words and:

![image](https://cloud.githubusercontent.com/assets/402057/6257005/ff9eae26-b7bc-11e4-8299-8b7b19f40883.png)

**Comment by stkdiretto** [comment]
JS still tbd. Another task for Open Data Day ;)

**Comment by namnatulco** [comment]
I considered doing that, but I wasn't sure which parts can be extracted. I guess we should do the same for the CSS while we're at it :)

**Comment by stkdiretto** [comment]
Done. Please mind we're working with the gh-pages branch!

**Comment by semaphor** [comment]
So the default branch should be [set](https://github.com/UlmApi/uulm-map/settings) to `gh-pages`?

**Comment by stkdiretto** [comment]
![image](https://cloud.githubusercontent.com/assets/402057/6278126/90805e9e-b894-11e4-9dc7-28851ece8220.png)
